/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment2;

import com.sun.jmx.defaults.JmxProperties;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author piiik98
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
        
        customerPanel();
        
        
    }
    
    public void totalPrice(){
        double total = 0.0;
        DecimalFormat format = new DecimalFormat("0.#");
        for (int i = 0; i < OrderTable.getRowCount(); i++){
            total += Double.parseDouble(OrderTable.getValueAt(i, 2).toString());
        }
        totalPrice.setText("Price: S$" + format.format(total).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        addFoodButton = new javax.swing.JButton();
        addDrinkButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        drinkTable = new javax.swing.JTable();
        deleteMenuButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        totalPrice = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        billPrice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billArea = new javax.swing.JTextArea();
        printButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Food");

        jLabel2.setText("Menu Of Kevin's Restaurant");

        jLabel3.setText("Drink");

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Menu", "Price"
            }
        ));
        jScrollPane2.setViewportView(foodTable);

        addFoodButton.setText("Add Food");
        addFoodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodButtonActionPerformed(evt);
            }
        });

        addDrinkButton.setText("Add Drink");
        addDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinkButtonActionPerformed(evt);
            }
        });

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Menu Order", "Price"
            }
        ));
        jScrollPane4.setViewportView(OrderTable);

        drinkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Menu", "Price"
            }
        ));
        jScrollPane5.setViewportView(drinkTable);

        deleteMenuButton.setText("Delete");
        deleteMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuButtonActionPerformed(evt);
            }
        });

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        totalPrice.setText("Price: S$0");

        jInternalFrame3.setVisible(true);

        jLabel4.setText("Kevin's Restaurant");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Bill");

        jLabel6.setText("James Cook University 2018");

        billPrice.setText("Price: S$");

        billArea.setColumns(20);
        billArea.setRows(5);
        billArea.setText("Menu Code\tMenu\tPrice");
        jScrollPane1.setViewportView(billArea);

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(billPrice)
                        .addGap(127, 127, 127))))
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addFoodButton)
                            .addComponent(addDrinkButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(printButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(totalPrice)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(confirmButton)
                                            .addComponent(deleteMenuButton))))
                                .addGap(14, 14, 14))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(backButton)
                .addGap(220, 220, 220)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(backButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteMenuButton)
                                .addGap(27, 27, 27)
                                .addComponent(totalPrice))
                            .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmButton)
                            .addComponent(printButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(addFoodButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDrinkButton)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFoodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodButtonActionPerformed
        // TODO add your handling code here: Button to add food to menu Order
        
        TableModel foodTbl= foodTable.getModel();
        int[] indexs = foodTable.getSelectedRows();
        Object[] rowf = new Object[3];
        DefaultTableModel modelOrder = (DefaultTableModel) OrderTable.getModel();
        
      
        for (int i = 0; i < indexs.length; i++){
            rowf[0] = foodTbl.getValueAt(indexs[i], 0);
            rowf[1] = foodTbl.getValueAt(indexs[i], 1);
            rowf[2] = foodTbl.getValueAt(indexs[i], 2);
            //rowf[2] = foodTbl.getValueAt(indexs[i], 2);
            modelOrder.addRow(rowf);
            
        }
        totalPrice();
        
        
                
        
//        DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
//        try{
//            int SelectedRowIndex = OrderTable.getSelectedRow();
//            model.;
//        } catch (Exception ex){
//            JOptionPane.showMessageDialog(null, ex);
//        }
    }//GEN-LAST:event_addFoodButtonActionPerformed

    private void addDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinkButtonActionPerformed
        // TODO add your handling code here: Button to add drink to menu order
        TableModel drinkTbl = drinkTable.getModel();
        int[] indexs = drinkTable.getSelectedRows();
        Object[] rowd = new Object[3];
        DefaultTableModel modelOrder = (DefaultTableModel) OrderTable.getModel();
        for (int i = 0; i < indexs.length; i++){
            rowd[0] = drinkTbl.getValueAt(indexs[i], 0);
            rowd[1] = drinkTbl.getValueAt(indexs[i], 1);
            rowd[2] = drinkTbl.getValueAt(indexs[i], 2);
            //rowd[2] = drinkTbl.getValueAt(indexs[i], 2);
            modelOrder.addRow(rowd);
        }
        totalPrice();
        
    }//GEN-LAST:event_addDrinkButtonActionPerformed

    private void deleteMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuButtonActionPerformed
        // TODO add your handling code here: Delete menu in menu order
        DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
        try{
            int SelectedRowIndex = OrderTable.getSelectedRow();
            model.removeRow(SelectedRowIndex);
            totalPrice();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_deleteMenuButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here: When the order finished and customer get a bill
        FileWriter pw;
        StringBuilder sb;
       
		try {
			pw = new FileWriter("doc/income.csv",true);
			sb = new StringBuilder();
                        TableModel model = OrderTable.getModel();
                        
                        billArea.setText("Menu Code \tMenu Name \tPrice \n");
                        for (int i = 0; i < model.getRowCount(); i++) {
                            for (int j = 0; j < model.getColumnCount(); j++) {
                                pw.write(model.getValueAt(i, j).toString() + ",");
                                billArea.setText(billArea.getText() + model.getValueAt(i, j).toString() + "\t");
                            }
                            pw.write("\n");
                            billArea.setText(billArea.getText() + "\n");
                        }
//			
			pw.flush();
			pw.close();      
                        
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
                
                
                
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here: Back to Welcome Panel
        Welcome welcome = new Welcome();
        welcome.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here: Print button will reset all input in menu order and will delete the text box on bill
        
        JOptionPane.showMessageDialog(null, "Bill printed");
        DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
        model.setRowCount(0);
        confirmButtonActionPerformed(evt);
        
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderTable;
    private javax.swing.JButton addDrinkButton;
    private javax.swing.JButton addFoodButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea billArea;
    private javax.swing.JLabel billPrice;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton deleteMenuButton;
    private javax.swing.JTable drinkTable;
    private javax.swing.JTable foodTable;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables

    private void customerPanel() {
        String fileName = "doc/data.csv";
	File file = new File(fileName); //Read about file
	List<List<String>> menuList = new ArrayList<>();
        

        try {
		Scanner inputMenu = new Scanner(file);
                System.out.println("Code \t\tFood\t\t\tPrice");
		while (inputMenu.hasNext()) {
                        String data = inputMenu.nextLine();
        		String[] items = data.split(",");
			menuList.add(Arrays.asList(items));
                        
			}
                inputMenu.close();
                        
                System.out.println("Food");
		int foodNo = 0;
		for (List<String> line : menuList) {
                    if (line.get(0).contains("F")) {
                        System.out.println(menuList.get(foodNo).get(0) + foodNo + "\t\t" + menuList.get(foodNo).get(1) + "\t\t $" + menuList.get(foodNo).get(2));
                        DefaultTableModel model = (DefaultTableModel) foodTable.getModel();
                        model.addRow(new Object[]{menuList.get(foodNo).get(0), menuList.get(foodNo).get(1), menuList.get(foodNo).get(2)});
			} 
            foodNo++;

		}
		System.out.println("\nDrinks");
		int drinkNo = 0;
		for (List<String> i : menuList) {
			if (i.get(0).contains("D")) {
				System.out.println(menuList.get(drinkNo).get(0) + drinkNo + "\t\t" + menuList.get(drinkNo).get(1) + "\t\t $" + menuList.get(drinkNo).get(2));
                                DefaultTableModel model = (DefaultTableModel) drinkTable.getModel();
                                model.addRow(new Object[]{menuList.get(drinkNo).get(0), menuList.get(drinkNo).get(1), menuList.get(drinkNo).get(2)});
			}
            drinkNo++;
		}
                        
                        
	} catch (FileNotFoundException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
        
        // Hide First Coloum of food Table
        foodTable.getColumnModel().getColumn(0).setWidth(0);
        foodTable.getColumnModel().getColumn(0).setMinWidth(0);
        foodTable.getColumnModel().getColumn(0).setMaxWidth(0); 
        
        // Hide First Coloum of drink Table
        drinkTable.getColumnModel().getColumn(0).setWidth(0);
        drinkTable.getColumnModel().getColumn(0).setMinWidth(0);
        drinkTable.getColumnModel().getColumn(0).setMaxWidth(0); 
        
        // Hide First Coloum of order food Table
        OrderTable.getColumnModel().getColumn(0).setWidth(0);
        OrderTable.getColumnModel().getColumn(0).setMinWidth(0);
        OrderTable.getColumnModel().getColumn(0).setMaxWidth(0); 
    }

        
}

